[tool.bumpversion]
current_version = "7.0.0"
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "CMakeLists.txt"
search = "project(c-questdb-client VERSION {current_version})"
replace = "project(c-questdb-client VERSION {new_version})"

[[tool.bumpversion.files]]
filename = "questdb-rs/Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "questdb-rs/README.md"
search = "Version {current_version} requires Rust"
replace = "Version {new_version} requires Rust"

[[tool.bumpversion.files]]
filename = "questdb-rs/README.md"
search = "https://github.com/questdb/c-questdb-client/tree/{current_version}/"
replace = "https://github.com/questdb/c-questdb-client/tree/{new_version}/"

[[tool.bumpversion.files]]
filename = "questdb-rs/README.md"
search = "https://github.com/questdb/c-questdb-client/blob/{current_version}/questdb-rs/"
replace = "https://github.com/questdb/c-questdb-client/blob/{new_version}/questdb-rs/"

[[tool.bumpversion.files]]
filename = "doc/COMPATIBILITY.md"
search = "for the {current_version} client"
replace = "for the {new_version} client"

[[tool.bumpversion.files]]
filename = "doc/RELEASING.md"
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = "doc/RELEASE_RUNBOOK.md"
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = "questdb-rs-ffi/Cargo.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "include/questdb/ingress/line_sender.hpp"
search = "questdb/c++/{current_version}"
replace = "questdb/c++/{new_version}"

[[tool.bumpversion.files]]
filename = ".bumpversion.toml"
search = "current_version = \"{current_version}\""
replace = "current_version = \"{new_version}\""
