trigger: none

variables:
  OS_MAPPING: none
  Windows_NT-X86: windows
  Darwin-X64: osx
  Darwin-ARM: armosx
  Linux-ARM: armlinux
  Linux-X64: linux

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              os: Linux
              generator: "CodeBlocks - Unix Makefiles"
            mac:
              imageName: "macos-latest"
              poolName: "Azure Pipelines"
              os: macOS
              generator: "CodeBlocks - Unix Makefiles"
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: false
          - script: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DQUESTDB_SYSTEM_TESTING=ON
            env:
              JAVA_HOME: $(JAVA_HOME_11_X64)
            displayName: "Build Makefile with CMake"
          - script: |
              cd build
              make
            env:
              JAVA_HOME: $(JAVA_HOME_11_X64)
            displayName: "Make"
          - script: (cd build && ctest --verbose)
            env:
              JAVA_HOME: $(JAVA_HOME_11_X64)
            displayName: "Tests"
