trigger: none

variables:
  OS_MAPPING: none
  Windows_NT-X86: windows
  Darwin-X64: osx
  Darwin-ARM: armosx
  Linux-ARM: armlinux
  Linux-X64: linux

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              os: Linux
              generator: "CodeBlocks - Unix Makefiles"
            mac:
              imageName: "macos-latest"
              poolName: "Azure Pipelines"
              os: macOS
              generator: "CodeBlocks - Unix Makefiles"
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: false
          # - task: JavaToolInstaller@0
          #   inputs:
          #   versionSpec: '11'
          #   jdkArchitectureOption: 'x64'
          #   jdkSourceOption: 'PreInstalled'
          - bash: echo $JAVA_HOME_11_X64
          - bash: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release #-DQUESTDB_SYSTEM_TESTING=ON
            displayName: "Build Makefile with CMake"
          - bash: (cd build && make)
            displayName: "Make"
          - bash: (cd build && ctest --verbose)
